### ISSUE TITLE
Wrong version in "version" file inside archive

### ISSUE THREAD

**Issue by abcdenis** [polm/unidic-py#9] opened 2021-06-30 22:27 UTC
Hi,
I have to prepare instance data without downloading data from internet so I dive into unidic downloading process.
What I did:
- issue `python -m unidic download` and download all the files
- get archive url from console and download it via curl utility then unpack
- all the files are the same except for `mecabrc`  and `version`
- `mecabr` created by unidic downloader
- version on module dir is `unidic-2.3.0+2020-10-08` but `2.3.0+20201004` inside archive
- I found out that actual version taken from `dicts.json` which is downloaded by default from github

This is confusing and waste time library's clients.

Could you please put actual UniDic version inside archive or do not put it at all?

Thank you.

**Comment by polm** [comment] 2021-07-02 07:59
Hey. This is a volunteer project by one person - me. Don't be rude. 

The version number indicates the base UniDic version (2.3.0) and the date of the release. The discrepancy in date between the file in the archive and the file generated by the download is because I made some updates to the code in this module without having to update the archive - I believe it was related to the AWS release. So the file in the archive is correct, but the file created when downloading is also correct.

I'm sorry you spent time chasing around these changes, but 

1. you can always use the [official UniDic release](https://unidic.ninjal.ac.jp/) instead 
2. you could just ask me about it before spending time on it
3. I'm still not clear how this is actually causing a problem for you

It's regrettable that the date format changed between versions, but I can't undo the old version. 

Since all this is working as intended I'm going to close this issue.

**Closed as completed by polm** 2021-07-02 07:59 UTC

**Comment by abcdenis** [comment] 2021-07-06 09:20
this is ok. I am preparing some service that should have the same data between any runs thats why I had to found out how to get stable data.
Changing version format is not an issue but `version` file data meaning changed from 'version of downloaded data` to 'version of code using that data' and this is confusing. Module version data is better to store on python code and not on somewhat version data. It's all up to you.
Thank you for your work!
