### ISSUE TITLE
Fix README.md

### ISSUE THREAD

**Issue by arg274** [polm/unidic-py#5] opened 2020-10-04 11:41 UTC
### System Specs

 - **OS:** Windows 10 (x86_64)
 - **Python Version:** 3.8
 - **fugashi Version:** 1.0.4

### Description
Using `tagger = fugashi.Tagger('-d{}'.format(unidic.DICDIR))` as per the readme causes fugashi to throw a `RuntimeError` due to the arguments being duplicated. However, using `tagger = fugashi.Tagger(unidic.DICDIR)` seems to resolve the issue.

**Comment by arg274** [comment] 2020-10-04 11:44
Not quite sure why this happens, as other threads here suggest that the initialisation in the readme works just fine for others. Changes in fugashi, perhaps?

**Comment by polm** [comment] 2020-10-05 12:07
Hm, that's weird. 

    tagger = fugashi.Tagger(unidic.DICDIR)

This should not work, if you just pass a path without a flag in front it shouldn't do anything useful and should give a `no such file or directory` error.

    tagger = fugashi.Tagger('-d{}'.format(unidic.DICDIR))

This might be failing because you're on Windows and the path quoting isn't working. Can you post the error details fugashi outputs and the value of `unidic.DICDIR`?

You can try this:

    tagger = fugashi.Tagger('-d "{}"'.format(unidic.DICDIR))

Also note that if you're using fugashi you actually don't have to pass the dictionary dir, unidic will be used by default if installed.

> ... due to the arguments being duplicated.

If the `-d` argument is duplicated that doesn't cause an error, the last one is used. So whatever the cause is that's not it.

**Comment by arg274** [comment] 2020-10-05 12:38
Using `tagger = fugashi.Tagger('-d{}'.format(unidic.DICDIR))
` gives:
```
Failed initializing MeCab. Please see the README for possible solutions:

    https://github.com/polm/fugashi

If you are still having trouble, please file an issue here, and include the
ERROR DETAILS below:

    https://github.com/polm/fugashi/issues

issueを英語で書く必要はありません。

------------------- ERROR DETAILS ------------------------
arguments: [b'fugashi', b'-C', b'-r', b'C:\\Users\\Redacted\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\unidic\\dicdir\\mecabrc', b'-d', b'C:\\Users\\Redacted\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\unidic\\dicdir', b'-dC:UsersRedactedAppDataLocalProgramsPythonPython38libsite-packagesunidicdicdir']
error message: param.cpp(69) [ifs] no such file or directory: C:UsersRedactedAppDataLocalProgramsPythonPython38libsite-packagesunidicdicdir\dicrc
Traceback (most recent call last):
  File "C:/Users/Redacted/PycharmProjects/RomajiDensity/test.py", line 8, in <module>
    tagger = fugashi.Tagger('-d{}'.format(unidic.DICDIR))
  File "fugashi\fugashi.pyx", line 313, in fugashi.fugashi.Tagger.__init__
  File "fugashi\fugashi.pyx", line 220, in fugashi.fugashi.GenericTagger.__init__
RuntimeError: Failed initializing MeCab
----------------------------------------------------------
```
My bad, the duplicate arguments are a non-issue. Quite obviously the Windows path wasn't formatted properly. But the default argument seems to be there.
However, using any of the options `fugashi.Tagger()`, `fugashi.Tagger(unidic.DICDIR)` and `tagger = fugashi.Tagger('-d "{}"'.format(unidic.DICDIR))` gives the desired result for me.

**Comment by polm** [comment] 2020-10-05 12:44
Glad it works! Still not sure why `fugashi.Tagger(unidic.DICDIR)` works but I'll fix the README and then close this.

**Closed as completed** 2020-10-05 12:50 UTC
